### ISSUE TITLE
how is this supposed to work ?

### ISSUE THREAD

**Issue by nsklaus** [ponyfleisch/hid-magictrackpad2#2]
hi, 
first thanks for the efforts in making magictrackpad2 to work on linux.
now i have questions, i have the module compiled, inserted, but still, nothing changed.
my trackpad is still one giant left mouse button only ;)   
```
klaus@nsbox:~$ lsmod |grep hid
hid_magictrackpad2     16384  0
hidp                   24576  2
bluetooth             540672  48 btrtl,hidp,btintel,bnep,btbcm,rfcomm,btusb
mac_hid                16384  0
hid_apple              16384  0
usbhid                 49152  0
hid                   118784  4 usbhid,hidp,hid_magictrackpad2,hid_apple
klaus@nsbox:~$ 
```

i've just build the module and inserted it. rebooted, and tested with and with usb cable.
maybe i need some configuration addition and tweaks in some places?
what would be missing ?

**Comment by D12EA177E12** [comment]
Did you read the README?  This module targets bluetooth *only*.
That said, this module still isn't ready (See [issue #1](https://github.com/ponyfleisch/hid-magictrackpad2/issues/1)).  Currently all basic functionalities work (including 2-finger scroll and 2-finger right-click) but there's no drag-and-drop support.  I've been following the progress of this github but it  looks like the author stopped working on this module.

**Comment by nsklaus** [comment]
i got it working .. great :)
now i want to disable the double click 'haptic feedback thingy..

**Comment by nsklaus** [comment]
i'm using xubuntu 17.10 by the way.
@D12EA177E12 how did you made it work ?

**Comment by D12EA177E12** [comment]
@nsklaus 
Do you have drag-and-drop support?

**Comment by nsklaus** [comment]
i've just tested, using thunar i could drag a file from one folder and drop it to another one.
if that's what you were asking ?
do you have any idea how i could disable the haptic feedback (applying more pressure gives a new click feedback ... i dislike that)

**Comment by D12EA177E12** [comment]
Yes, that would be a drag-and-drop.  In my case, dragging doesn't work at all.
Just to make sure we're on the same page, you managed to get drag-and-drop working under Bluetooth, right?

**Comment by nsklaus** [comment]
yes if we agree that my simple test is all you asked for to call it 'drag and drop support'
so, i have drag and drop working, under bluetooth. so you know it can work.
i have "tap to click" setting, so double tap allow me to grab-move a window border or an icon etc ..

and also i just managed to tweak the source in the most ugly workaround to get rid of "force haptic double-click terrible thing" (fhdtt)  i've just increased the amount of pressure required by 10 :)
`#define PRESSURE_FORCE_THRESHOLD 1000  // (was 140)`

**Comment by ponyfleisch** [comment]
Hi @nsklaus and @D12EA177E12 

Nice to see that there is interest in the module. I'll try to muster up some energy to make it more stable. Apologies for the radio silence.

**Comment by nsklaus** [comment]
good to hear :)
after using your driver for a little, i have to say it works quite well.
the only two issues i had so far:

- i am forced to manually do a modprobe remove/insert after each reboot, like so:
`modprobe -r hid_generic hid_magictrackpad2` 
`modprobe hid_magictrackpad2`

- and also i found the lack of usb cable support a bit disapointing.
could you put back the usb support too ? 
(for when the trackpad is plugged in and charging)

thanks for your work on this. 
i'm happy to finaly be able to use the mtrackpad2 on linux :)

**Comment by ponyfleisch** [comment]
Hi @nsklaus yes i'm working on this now. It'll be a bit of a rewrite though.
