### ISSUE TITLE
manual remove/insert module upon each reboot

### ISSUE THREAD

**Issue by nsklaus** [ponyfleisch/hid-magictrackpad2#3]
it seems i need to run this after each reboot:
`modprobe -r hid_generic; modprobe hid_magictrackpad2`
i was wondering if there was a way to avoid this step ?
as a workaround maybe i can put this line somewhere so it gets automated and i don't need to do it manualy each time ?

thanks

**Comment by ponyfleisch** [comment]
Apologies for not getting back sooner. To make this work it should be packaged into a DKMS similar to https://github.com/robbi5/magictrackpad2-dkms. I have no time/motivation at the moment to do this unfortunately, feel free to give it a go and submit a pull request if you want.

**Comment by D12EA177E12** [comment]
Have you tried including/updating your initramfs to include the module (assuming that it's not already in there)?
