### ISSUE TITLE
Motion and clicks not registered until multiple fingers registered

### ISSUE THREAD

**Issue by MeanderingCode** [ponyfleisch/hid-magictrackpad2#6]
The module works very well with the synaptics driver with one difficult glitch. Single tap or move does not register input events until after a second finger is added and removed from the trackpad.
evtest registers EV_ABS events.

If the issue is with synaptics configuration, the options weren't obvious to me. I would be happy to help improve the driver, though I did not find a succinct source of information about the input events interface and the raw_event function is a little too byzantine for a first glance. If pointed at an introduction to the interfaces and object structures for the input APIs, I may be able to find some time for this.

**Comment by ponyfleisch** [comment]
Hi @MeanderingCode. In case you have not seen yet, there is now a new driver by @robotrovsky that you can find here: https://github.com/robotrovsky/Linux-Magic-Trackpad-2-Driver

As i'm at the moment using mostly macOS on my primary workstation i can't check my working configuration.
